name: example
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.2
  share_plus: ^6.1.0
  package_info_plus: ^3.0.1
  firebase_core: ^2.1.0
  shared_preferences: ^2.0.15
  internet_connection_checker: ^1.0.0+1
  flutter_riverpod: ^2.0.2

dev_dependencies:

  flutter_test:
    sdk: flutter
  starter:
    path: ../

  
  
  
  
  
  flutter_lints: ^2.0.0
  flutter_app_name: ^0.1.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0






flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  


